"""empty message

Revision ID: a275ee1a7ea9
Revises: c5bd17fb8e66
Create Date: 2024-01-29 15:58:41.629525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a275ee1a7ea9'
down_revision = 'c5bd17fb8e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_token', sa.String(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_token'], ['token'])
        batch_op.drop_column('book_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_token')

    # ### end Alembic commands ###
